version: 2

sources:
  

  - name: VISIONBOOKS
    database: vision
    schema: VISIONBOOKS
    
    tables:
      - name: AUTHORS
        columns:
          - name: au_id
            tests:
              - unique
          
      - name: TITLES
        columns:
          - name: title_id
            tests:
              - unique  
          
      - name: SALES
        columns:
          - name: sales_id
            tests:
              - unique 
              
      - name: PUBLISHERS
        columns:
          - name: pub_id
            tests:
              - unique
          
      - name: DISCOUNTS
        columns:
          - name: discount_id
            tests:
              - unique
            
          
      - name: Reader
        columns:
          - name: reader_id
            tests:
              - unique
          
          
      
      -  name: ReaderSales
         tests:
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns:
                  - reader_id
                  - sales_id
                  
      -  name: TITLEAUTHORS
         tests:
            - dbt_utils.unique_combination_of_columns:
                combination_of_columns:
                  - title_id
                  - au_id
      
            




